// <auto-generated />
using System;
using FocusDesk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusDesk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607081356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FocusDesk.Models.AppWhitelistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WhitelistEntries");
                });

            modelBuilder.Entity("FocusDesk.Models.BlockedSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BlockedSites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Social",
                            Domain = "facebook.com",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 2,
                            Category = "Social",
                            Domain = "instagram.com",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 3,
                            Category = "Social",
                            Domain = "twitter.com",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 4,
                            Category = "Social",
                            Domain = "x.com",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 5,
                            Category = "Social",
                            Domain = "tiktok.com",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 6,
                            Category = "Video",
                            Domain = "youtube.com",
                            IsEnabled = false
                        },
                        new
                        {
                            Id = 7,
                            Category = "News",
                            Domain = "reddit.com",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 8,
                            Category = "Video",
                            Domain = "twitch.tv",
                            IsEnabled = false
                        });
                });

            modelBuilder.Entity("FocusDesk.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FocusDesk.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedPomodoros")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedPomodoros")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("FocusDesk.Models.Session", b =>
                {
                    b.HasOne("FocusDesk.Models.TaskItem", "TaskItem")
                        .WithMany("Sessions")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("FocusDesk.Models.TaskItem", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
